trigger:
  branches:
    include:
      - main

variables:
  # Set your ACR name and image name
  ACR_NAME: 'songxiangcr'
  IMAGE_NAME: 'rhino'

stages:
- stage: BuildAndPush
  displayName: 'Build and Push Docker Image'
  jobs:
  - job: Build
    displayName: 'Build and Push to ACR'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'songxiangcr'  # Set in Project > Project Settings > Service connections
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          echo "Logging in to ACR"
          az acr login --name $ACR_NAME

          echo "Building Docker image"
          docker build -t $ACR_NAME.azurecr.io/$IMAGE_NAME:$(Build.BuildId) .

          echo "Pushing image"
          docker push $ACR_NAME.azurecr.io/$IMAGE_NAME:$(Build.BuildId)

          echo "Tagging latest (optional)"
          docker tag $ACR_NAME.azurecr.io/$IMAGE_NAME:$(Build.BuildId) $ACR_NAME.azurecr.io/$IMAGE_NAME:latest
          docker push $ACR_NAME.azurecr.io/$IMAGE_NAME:latest